const ADMIN_PASSWORD = ['4','5','5','0'].join('');
const NORMAL_TIME = 60;
const TEST_TIME = 30;
const LETTERS = ['a','b','c','d','e','f','g','h'];
const ANGLES = [30,45,60,120,135,150];
let player={studentNo:'',name:''}, state=null, timerId=null, locked=false;
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function pair(type,p){if(type==='corresponding')return p+4; if(p===2)return 7;if(p===3)return 6;if(p===6)return 3;if(p===7)return 2;return (p+4)%8}
function labels(){let x=shuffle(LETTERS),m={};x.forEach((v,i)=>m[i]=v);return m}
function diagram(m){let s='<svg viewBox="0 0 600 300"><style>.g{stroke:#111827;stroke-width:4;fill:none;stroke-linecap:round}.t{font:700 22px system-ui;fill:#111827}</style><path class="g" d="M45 105H555M45 205H555M85 270L515 40"/><circle cx="207" cy="105" r="4"/><circle cx="393" cy="205" r="4"/>';const os=[[-58,-17],[40,-17],[40,29],[-58,29]];for(let i=0;i<4;i++){s+=`<text class="t" x="${207+os[i][0]}" y="${105+os[i][1]}">${m[i]}</text>`}for(let i=0;i<4;i++){s+=`<text class="t" x="${393+os[i][0]}" y="${205+os[i][1]}">${m[i+4]}</text>`}return s+'</svg>'}
function sizeDiagram(q){return `<svg viewBox="0 0 600 300"><style>.g{stroke:#111827;stroke-width:4;fill:none;stroke-linecap:round}.t{font:700 21px system-ui;fill:#111827}.d{stroke:#6b7280;stroke-width:1.5;stroke-dasharray:5 5}</style><path class="g" d="M45 105H555M45 205H555M85 270L515 40"/><path class="d" d="M45 80H555M45 230H555"/><circle cx="207" cy="105" r="4"/><circle cx="393" cy="205" r="4"/><text class="t" x="${207+q.ao[0]}" y="${105+q.ao[1]}">a</text><text class="t" x="${393+q.go[0]}" y="${205+q.go[1]}">${q.value}°</text></svg>`}
const offsets=[[-58,-17],[40,-17],[40,29],[-58,29]];
function newQuestion(){let type=1+Math.floor(Math.random()*4);if(type<3){let m=labels(),p=+Object.keys(m).find(k=>m[k]==='a'),ans=m[pair(type===1?'corresponding':'alternate',p)];return{type,m,answer:ans,text:type===1?'각 a의 동위각은?':'각 a의 엇각은?'}}let target=Math.floor(Math.random()*4),given=type===3?target:({0:2,1:3,2:0,3:1}[target]),v=pick(ANGLES);return{type,answer:String(v),text:'각 a의 크기는?',ao:offsets[target],go:offsets[given],value:v}}
function render(){let q=state.q=newQuestion();$('questionNo').textContent=state.index+1;$('questionType').textContent=q.type===1?'동위각':q.type===2?'엇각':'평행선에서 각의 크기';$('questionText').textContent=q.text;$('diagram').innerHTML=q.type<3?diagram(q.m):sizeDiagram(q);$('answerInput').value='';$('answerInput').disabled=locked;if(!locked)$('answerInput').focus()}
function start(test=false){if(!test){player.studentNo=$('studentNo').value.trim();player.name=$('studentName').value.trim();if(!player.studentNo||!player.name){$('homeMessage').textContent='학생 번호와 이름을 입력하세요.';return}}state={score:0,correct:0,wrong:0,index:0,test};locked=false;show('game');$('score').textContent='0';let t=test?TEST_TIME:NORMAL_TIME;$('timer').textContent=t;render();clearInterval(timerId);timerId=setInterval(()=>{t--;$('timer').textContent=t;if(t<=0)end()},1000)}
function submit(e){e.preventDefault();if(!state||locked)return;let ok=$('answerInput').value.trim().toLowerCase()===state.q.answer.toLowerCase();if(ok){state.score++;state.correct++;$('score').textContent=state.score;$('feedback').textContent='정답! +1점';state.index++;render()}else{state.score-=2;state.wrong++;$('score').textContent=state.score;locked=true;$('answerInput').disabled=true;$('feedback').textContent='오답! -2점 · 3초 동안 입력할 수 없습니다.';setTimeout(()=>{if(state){locked=false;state.index++;render()}},3000)}}
function end(){if(!state)return;clearInterval(timerId);let x=state;state=null;$('finalScore').textContent=x.score;$('correctCount').textContent=x.correct;$('wrongCount').textContent=x.wrong;$('saveStatus').textContent=x.test?'테스트 모드: 랭킹에는 저장하지 않습니다.':'게임 기록 저장 기능은 Firebase 연결 후 활성화됩니다.';show('result')}
$('startBtn').onclick=()=>start(false);$('testBtn').onclick=()=>start(true);$('answerForm').onsubmit=submit;$('homeBtn').onclick=()=>show('home');$('adminBtn').onclick=()=>show('adminLogin');$('adminLoginBtn').onclick=()=>{if($('adminPassword').value===ADMIN_PASSWORD){$('adminPassword').value='';show('admin')}else $('adminLoginMessage').textContent='비밀번호가 올바르지 않습니다.'};document.querySelectorAll('.backHome').forEach(b=>b.onclick=()=>show('home'));$('resetBtn').onclick=()=>alert('Firebase 연결 후 실제 랭킹 데이터를 초기화하도록 설정할 수 있습니다.');
